### ISSUE TITLE
stdlib sources?

### ISSUE THREAD

**Issue by tunix** [flathub/org.freedesktop.Sdk.Extension.rust-stable#107]
When I use this SDK extension with Intellij IDEA, it complains about not being able to find stdlib sources. Are they part of this package? If not, is it possible to add them?

**Comment by twelho** [comment]
Had the same issue, dropping caches as described in https://github.com/intellij-rust/intellij-rust/issues/8364#issuecomment-1089054738 (located at `~/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/cache` for the Flatpak version) before each launch seems to be a functional workaround. Upstream issue might be https://github.com/rust-lang/cargo/issues/10096 as described in the aforementioned comment.
