### ISSUE TITLE
error: linker `aarch64-linux-gnu-gcc` not found

### ISSUE THREAD

**Issue by olof-nord** [flathub/org.freedesktop.Sdk.Extension.rust-stable#118]
Is there any specific configuration needed to build on aarch64?

Looking at the manifest, I get the impression that a aarch64 linker is already in place.

Full error log here: https://flathub.org/builds/#/builders/45/builds/6122

**Comment by bilelmoussaoui** [comment]
No idea what is going wrong, we have plenty of rust apps built and published for aarch64 already

**Comment by bilelmoussaoui** [comment]
the logs are no longer available though, can you still reproduce the issue?

**Comment by alatiera** [comment]
Please reopen with fresh logs if this still an issue.

Thanks!
