### ISSUE TITLE
Include cargo-c

### ISSUE THREAD

**Issue by lw64** [flathub/org.freedesktop.Sdk.Extension.rust-stable#188]
I need to install the gst-rs-plugins in my flatpak app, and that needs cargo-c installed during build time. I could do that just for my app, but I think it would make sense to have it in the sdk, as other rust projects that want to provide a shared library and package config files will need it too, to make them accessible to non-rust apps.

**Comment by hfiguiere** [comment]
this is not in the scope of the sdk.

**Comment by alatiera** [comment]
I don't think its that far off, cargo-c is mostly used to install the .so, generate .pc files and install headers for components that provide a cffi
