### ISSUE TITLE
Update/Upgrade to Freedesktop 18.08

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.freedesktop.Sdk.Extension.rust-stable#2]
flathub/org.freedesktop.Sdk.Extension.gcc8#3
flathub/org.freedesktop.Sdk.Extension.openjdk10#5

Thanks!

**Comment by danigm** [comment]
Updated, thank you.

**Comment by barthalion** [comment]
Correct me if I'm mistaken, but AFAIK Freedesktop SDK team provides now this extension, so @danigm's commit effectively overwrote what we import on Flathub. @alexlarsson  @jjardon

**Comment by jjardon** [comment]
Hey! @alatiera is maintaining this at the moment; probably he can give more precise details

**Comment by alatiera** [comment]
> Sorry for my ignorance on this topic, but how is the extension provided by the SDK itself? Rust compiler is inside the freedesktop SDK without the need of this extension or there's other method how the SDK provides this extension on flathub?

The Rust that comes from the fdo-sdk repo, is not part of the `org.Freedesktop.Sdk` itself but rather an extension like this one. It lives on the fdo repo cause we need rust to build sdk dependencies, like `librsvg` anyway but its distributed as an Sdk-Extension.

To avoid confusion I am gonna be referring to the Extension that lives in the fdo repo as 18.08 and this one as 1.6.

They both have same update policy given that Rust does not yet have a stable ABI. I update the 18.08 extension whenever there's a new release out.

However their ABI of the 2 extensions, as a whole, is different. The 18.08 is bootstrapped from source, wheres 1.6, this one, is redistributing precompiled binaries. 

Additionally, in the 1.6 extension included `rustfmt` and `rls`(Rust language server) into its `/bin` folder. We should probably include those as well in `18.08` but none has worked on it.

Going forward we could maintain the Rust extensions strainght from the freedesktop-sdk repo, but for now I think this extension should stay at the 1.6 runtime, given that there still actively used runtimes like `GNOME 3.28` that are not compatible with the `18.08` extension.

**Comment by barthalion** [comment]
@alatiera Yeah, I know it all – my concern is that with https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/commit/3833451e4d27f961b8d23864b4b753aeddf9c5d6 buildbot just overwrote what we import from your remote with the triggered build.

**Comment by alatiera** [comment]
oh indeed, that's a problem. @danigm could you revert 3833451  so we will continue to serve both fd.o sdk 1.6 and 18.08 with Sdk extensions?

**Comment by danigm** [comment]
Done, I've just reverted that commit.
