### ISSUE TITLE
Where do I create a global config.toml file?

### ISSUE THREAD

**Issue by carvalhods** [flathub/org.freedesktop.Sdk.Extension.rust-stable#302]
I'm using Gnome Builder + rust-stable flatpak extension and I would like to create a global `config.toml` file.
In a common environment, I just create a `$HOME/.cargo/config.toml` file, but apparently this file is not being read. Is it possible to create a global config.toml with the rust-stable flatpak version? Thanks.

**Comment by hfiguiere** [comment]
this is a question for gnome builder and how it has access to $HOME in that case.

**Comment by carvalhods** [comment]
Ok, tks.
