### ISSUE TITLE
Bundle rustup?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.freedesktop.Sdk.Extension.rust-stable#4]
Rust language server requires `rustup` and complains when missing.

**Comment by danigm** [comment]
This extension install rust using the standalone installer so `rustup` is not there and it's not part of this extension. If you need rustup for your flatpak you should add to your manifest or create a new extension for that.

https://forge.rust-lang.org/other-installation-methods.html#standalone-installers

**Comment by teohhanhui** [comment]
This causes DX issues such as https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-nightly/issues/282
