### ISSUE TITLE
Need help with building cargo project

### ISSUE THREAD

**Issue by sireliah** [flathub/org.freedesktop.Sdk.Extension.rust-stable#41]
Hi!

I have some trouble building a binary using rust-stable extension. Perhaps this can be solved by providing an example how to correctly build such project. Here's what is happening:

```bash
$ flatpak-builder --force-clean  flatpak/ com.sireliah.Dragit.yml
(...)
Running: export PATH=/usr/lib/sdk/rust-stable/bin/:$PATH && cargo build --release
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get `async-std` as a dependency of package `dragit v0.4.0 (/run/build/dragit)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
Error: module dragit: Child process exited with code 101
```

The above error is network related. I've made some experiments and it seems to be a general problem, because I don't seem to have network access in the build container, not to mention DNS:
```bash
Running: curl 1.1.1.1
curl: (7) Couldn't connect to server
 ```
Here's my manifest (please note the `--share=network`):

```yaml
app-id: com.sireliah.Dragit
runtime: org.freedesktop.Platform
runtime-version: '20.08'
sdk: org.freedesktop.Sdk
finish-args:
  - --share=network
command: dragit
modules:
  - name: dragit
    buildsystem: simple
    build-commands:
      - export PATH=/usr/lib/sdk/rust-stable/bin/:$PATH && cargo build --release
    sources:
      - type: git
        url: https://github.com/sireliah/dragit.git
```

Do you see anything fundamentally wrong in my manifest? I wasn't able to find any example of building Rust in Flatpak, so maybe once we solve the problem I can add example to the repo.

What could be the reason for the network problem? When I run custom command, I have access to the host network:
```bash
$ flatpak-builder -v --run  flatpak/ com.sireliah.Dragit.yml bash
(...)
bash-5.1$ curl crates.io
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

**Comment by sireliah** [comment]
By rubber-ducking this ticket I've found that you're supposed to provide cargo deps as local files and build them locally:

https://github.com/flathub/com.uploadedlobster.peek/blob/master/com.uploadedlobster.peek.json

**Comment by bilelmoussaoui** [comment]
This should cover enough details https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo or https://belmoussaoui.com/article/8-how-to-flatpak-a-rust-application if you want more details
