### ISSUE TITLE
Bundle lldb

### ISSUE THREAD

**Issue by alatiera** [flathub/org.freedesktop.Sdk.Extension.rust-stable#44]
We ship the `rust-lldb` binary, but we are missing `lldb` itself to make use of it. It's not part of the  [Sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/768).

```
alatiera@almost-working ~> flatpak run org.gnome.Sdk//3.38
[📦 org.gnome.Sdk ~]$ source /usr/lib/sdk/rust-stable/enable.sh 
[📦 org.gnome.Sdk ~]$ rust-lldb 
lldb not found! Please install it.
[📦 org.gnome.Sdk ~]$ 
```

**Comment by Erick555** [comment]
lldb is now present in https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11

```
❯ flatpak run --devel org.freedesktop.Sdk//20.08
[📦 org.freedesktop.Sdk ~]$ source /usr/lib/sdk/rust-stable/enable.sh
[📦 org.freedesktop.Sdk ~]$ source /usr/lib/sdk/llvm11/enable.sh
[📦 org.freedesktop.Sdk ~]$ rust-lldb
(lldb) command script import "/usr/lib/sdk/rust-stable/lib/rustlib/etc/lldb_lookup.py"
error: module importing failed: This script interpreter does not support importing modules.
(lldb) 
```

**Comment by Erick555** [comment]
It's fixed now:
```
flatpak run --devel org.freedesktop.Sdk//20.08    
[📦 org.freedesktop.Sdk ~]$ source /usr/lib/sdk/rust-stable/enable.sh 
[📦 org.freedesktop.Sdk ~]$ source /usr/lib/sdk/llvm11/enable.sh 
[📦 org.freedesktop.Sdk ~]$ rust-lldb
(lldb) command script import "/usr/lib/sdk/rust-stable/lib/rustlib/etc/lldb_lookup.py"
(lldb) command source -s 0 '/usr/lib/sdk/rust-stable/lib/rustlib/etc/lldb_commands'
Executing commands in '/usr/lib/sdk/rust-stable/lib/rustlib/etc/lldb_commands'.
(lldb) type synthetic add -l lldb_lookup.synthetic_lookup -x ".*" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)String$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^&str$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^&\\[.+\\]$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::ffi::([a-z_]+::)+)OsString$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Vec<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)VecDeque<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)BTreeSet<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)BTreeMap<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::collections::([a-z_]+::)+)HashMap<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::collections::([a-z_]+::)+)HashSet<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Rc<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Arc<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)Cell<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)Ref<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)RefMut<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)RefCell<.+>$" --category Rust
(lldb) type category enable Rust
(lldb) 
```

@alatiera is this satisfactory for solution you? I think it's not worth to duplicate lldb maintenance when users can just install one more thing.

**Comment by alatiera** [comment]
Thanks! I haven't looked at this much yet, just opened an issue to not lose track of this.

Looks like this could work if you have both extensions installed, but then apps would need to know to depend on both. It won't work ootb nor can extensions depend on one another. And then apps would also have to keep track of the llvm version rust uses and figure out when to udpate and stuff. I will try to find some time to look at this further in the days ahead.

**Comment by Erick555** [comment]
> then apps would need to know to depend on both

Apps can't depend on either at runtime and lldb isn't needed at build. Generally apps like gnome builder doesn't have any Sdk deps and users are expected to install all additional tooling they need for debug/development which then will just work without any explicit dependencies like in a distro packages so I think there is nothing unusual.

> And then apps would also have to keep track of the llvm version rust uses and figure out when to udpate and stuff. 

I don't understand what do you mean here. Rust extension isn't tied to any llvm or lldb version and apps don't have anything to update regarding to that

**Comment by alatiera** [comment]
> Apps can't depend on either at runtime and lldb isn't needed at build. Generally apps like gnome builder doesn't have any Sdk deps and users are expected to install all additional tooling they need for debug/development which then will just work without any explicit dependencies like in a distro packages so I think there is nothing unusual.

It's not unusual, but its not nice. Having a working debugger ootb I think is very important.

> I don't understand what do you mean here. Rust extension isn't tied to any llvm or lldb version and apps don't have anything to update regarding to that

rustc raises the minimum llvm requirement from time to time. For example last year it was llvm 8.0+. For the last releases I think it wants llvm 11 or 12.

**Comment by Erick555** [comment]
> It's not unusual, but its not nice. Having a working debugger ootb I think is very important.

It's your call but I think building anything here complicates maintenance which is pretty straightforward atm. This will be even worse if/when runtime drops llvm as you would need llvm extension to build lldb then. Moreover if user has both rust and llvm extensions installed then it won't be obvious which one will be loaded as it'll depend on specific PATH order.

> rustc raises the minimum llvm requirement from time to time. For example last year it was llvm 8.0+. For the last releases I think it wants llvm 11 or 12.

Nope. Latest release is at [llvm 9](https://github.com/rust-lang/rust/commit/f8a32e9a4efcbbbf79cbaeec9c3f4346e5348d76) and only master (not even beta) bumped it to [llvm 10](https://github.com/rust-lang/rust/commit/7d872f538efc5cb3786c3aa0a6654bae7a67ec63) recently. For my understanding this is for building rust so I'm not sure if it matters for lldb but even then you won't be able to keep it compatible while PR are merged automatically by bot. Obviously disabling auto updates will add the burden I mentioned above. As for extension the plan is to make new one for every llvm major release so users could always found compatible one.

**Comment by alatiera** [comment]
Indeed, I think its best to add the llvm extension if we need lldb as you said.

**Comment by Erick555** [comment]
Since llvm extension is now [recommended](https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable#mold) for mold maybe rust-lldb case could be mentioned in readme as well.

**Comment by alatiera** [comment]
Yea that's what I was thinking as well
