### ISSUE TITLE
unstable version of the Sdk?

### ISSUE THREAD

**Issue by muelli** [flathub/org.freedesktop.Sdk.Extension.rust-stable#5]
This is more of a question which might become an actionable bug report.

Deltachat needs rust nightly (cf. https://github.com/flathub/chat.delta.desktop/pull/20) and I am wondering whether an "unstable Sdk" would be acceptable.  If so, I might dedicate some time generously copy and pasting the existing stable one and include the nightly compiler instead.

**Comment by danigm** [comment]
The problem with nightly is how often do you update the extension. It'll be useful to have the Sdk extension for nightly but I don't know if it's convenience to have the nightly extension in flathub. Another option could be to use the flathub beta repository, but I don't know.

**Comment by gdesmott** [comment]
I'll need nightly as well to build my project (because of Rocket) so I'm interested in this as well.

**Comment by danigm** [comment]
> I'll need nightly as well to build my project (because of Rocket) so I'm interested in this as well.

If you need that you can add rust nightly as a source in your manifest, here you've an example manifest:

https://github.com/danigm/rust-nightly-sample/blob/master/net.danigm.rust-nightly.json

**Comment by muelli** [comment]
cool.

There is another example here: https://github.com/flathub/chat.delta.desktop/blob/415512b45fe1224a973a227be658521b9a3deb57/chat.delta.desktop.yml#L100

**Comment by gdesmott** [comment]
> > I'll need nightly as well to build my project (because of Rocket) so I'm interested in this as well.
> 
> If you need that you can add rust nightly as a source in your manifest, here you've an example manifest:
> 
> https://github.com/danigm/rust-nightly-sample/blob/master/net.danigm.rust-nightly.json

Great thanks. Used that and managed to build my app.

Only problem is I'm getting unusable backtrace from rust despite running with `RUST_BACKTRACE=full`. Is that working for you?
