### ISSUE TITLE
cargo install subcommands

### ISSUE THREAD

**Issue by d3m1gd** [flathub/org.freedesktop.Sdk.Extension.rust-stable#59]
Trying to install cargo subcommands fails, because bin directory is a link to a read only location.

Launching following command from inside Code OSS flatpak:

```
cargo install cargo-outdated
```

Causes the following error:

```
error: Read-only file system (os error 30) at path "/home/user/.var/app/com.visualstudio.code-oss/data/cargo/bin/cargo-installxiJVhL"
```

Compilations finishes successfully, but binary can't be installed.

**Comment by bilelmoussaoui** [comment]
That's an issue you should report against the Code OSS flatpak, nothing is related to the SDK here.
