### ISSUE TITLE
Build for org.freedesktop.Sdk//21.08

### ISSUE THREAD

**Issue by teohhanhui** [flathub/org.freedesktop.Sdk.Extension.rust-stable#74]

**Comment by alatiera** [comment]
This was already done in 21c19acc713439f4fb9593b633b034c8d0aaf19c, its not available?

**Comment by Lctrs** [comment]
It's available. We should make `branch/21.08` the default branch to get auto updates on this branch instead of `branch/20.08`.

**Comment by alatiera** [comment]
Yes, need an admin to do it.

**Comment by Alexander-Wilms** [comment]
Now it works: https://github.com/flathub/com.play0ad.zeroad/pull/32
