### ISSUE TITLE
rust 1.42.0

### ISSUE THREAD

**Issue by jangernert** [flathub/org.freedesktop.Sdk.Extension.rust-stable#8]
[Rust 1.42.0](https://blog.rust-lang.org/2020/03/12/Rust-1.42.html) was release today. As of this post the SDK is still on version 1.40.0. Can we please get an update? I'm specifically asking because one of my dependencies needs rust 1.41.0. So as of now my CI/CD pipeline [keeps failing](https://gitlab.com/news-flash/news_flash_gtk/-/jobs/469592429) for that reason.

I'm consuming this SDK via `registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:3.36` btw.

Thank you.

**Comment by danigm** [comment]
I would recommend you to use the latest `org.freedesktop.Sdk` instead of this old version. In any case, I'll create a new release with the latest version of rust just now.

**Comment by jangernert** [comment]
Cool, thank you.

Like I said. I'm not using this SDK directly, but through a [gnome-runtime-image](https://gitlab.gnome.org/GNOME/gnome-runtime-images/-/blob/master/sdk-bundles/rust-bundle.template).

If your advice is to use `org.freedesktop.Sdk` directly (I'm guessing it contains the latest rust release?)
should I file a bug against the gnome image to switch?

**Comment by barthalion** [comment]
cc @alatiera

**Comment by danigm** [comment]
Yes, if you use the latest freedesktop-sdk or gnome-sdk (it's based on freedesktop) you'll get the latest rust extension by default.

**Comment by alatiera** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2356

and the backport for 19.08

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2314

**Comment by jangernert** [comment]
Oh, okay. So from what I understand I'm waiting for the 19.08 backport to get merged.
